spring:
  application:
    name: library
  server:
    port: 0
  eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway:
    baselineOnMigrate: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
properties:
  postgres:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=otus
    username: postgres
    password: example
logging:
  level:
    web: debug

jwt:
  secret: CuKq7g3eOzsc3FKu8O7hoeo0IegTHCKHBKkkN3XdCCwIZw5p5x