spring:
  flyway:
    baselineOnMigrate: true

#  sql:
#    init:
#      mode: always
#      data-locations: V2__add_data.sql
#      schema-locations: schema.sql
#  h2:
#    console:
#      path: /h2-console
#      settings:
##        web-allow-others: true
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    show-sql: true
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=otus
    user: postgres
    password: example
    enabled: true
properties:
  postgres:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=otus
    username: postgres
    password: example

