spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    auth:
      path: /**
    store:
      path: /api/v1/**/**
  sensitiveHeaders: ""
server:
  port: 8082

logging:
  level:
    root: debug
