spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway:
    baselineOnMigrate: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

    show-sql: true
properties:
  postgres:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=otus
    username: postgres
    password: example

logging:
  file:
    path: ./src/main/resources

resilience4j.circuitbreaker:
  instances:
    myCircuitBreaker:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10