version: '3'
services:
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PROPERTIES_POSTGRES_URL=jdbc:postgresql://postgres:5432/db
      - PROPERTIES_POSTGRES_USERNAME=postgres
      - PROPERTIES_POSTGRES_PASSWORD=postgres
  postgres:
    container_name: mydb
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

