spring:
  flyway:
    baselineOnMigrate: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

    show-sql: true
properties:
  postgres:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=otus
    username: postgres
    password: example

